name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - "14.x"
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm test
        working-directory: ./test

      - name: Build
        run: npm build
        working-directory: ./packages/helm-parser

  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
    needs:
      - build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        run: |
          VERSION=$(nbgv get-version -v NpmPackageVersion)
          echo Version is ${VERSION}
          lerna version ${VERSION} --no-push --no-git-tag-version --exact -y

      - name: Lerna publish
        if: github.ref == 'refs/heads/master'
        run: |
          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
          npm config set access public
          npx lerna publish from-package --yes --contents pkg
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
